language: node_js
node_js:
  - node
services:
  - docker

cache:
  directories:
    - "node_modules"

before_script:
  - npm i -g serverless nexus prisma
  - echo "DATABASE_URL=${DATABASE_URL}" > prisma/.env

script: npm run generate

after_script:
  - npm ci
  - docker build -t gql:latest .
  - pip install awscli
  - export PATH=$PATH:$HOME/.local/bin
  - export AWS_ACCOUNT_ID="$(aws sts get-caller-identity --output text --query 'Account')"
  - eval "$(aws ecr get-login --region ap-south-1 --no-include-email)"
  - docker tag gql:latest "${AWS_ACCOUNT_ID}".dkr.ecr."${AWS_REGION}".amazonaws.com/gql:latest
  - docker push "${AWS_ACCOUNT_ID}".dkr.ecr."${AWS_REGION}".amazonaws.com/gql:latest

