language: node_js
node_js:
  - node
services:
  - docker

cache:
  directories:
    - "node_modules"

before_script:
  - npm i -g serverless
  - echo "DATABASE_URL=${DATABASE_URL}" > prisma/.env

script:
  - echo "No Tests"

after_script:
  - docker build -t gql:"${TRAVIS_BUILD_NUMBER}" .
  - pip install awscli
  - export PATH=$PATH:$HOME/.local/bin
  - export AWS_ACCOUNT_ID="$(aws sts get-caller-identity --output text --query 'Account')"
  - eval "$(aws ecr get-login --region ap-south-1 --no-include-email)"
  - docker tag gql:"${TRAVIS_BUILD_NUMBER}" "${AWS_ACCOUNT_ID}".dkr.ecr."${AWS_REGION}".amazonaws.com/gql:"${TRAVIS_BUILD_NUMBER}"
  - docker push "${AWS_ACCOUNT_ID}".dkr.ecr."${AWS_REGION}".amazonaws.com/gql:"${TRAVIS_BUILD_NUMBER}"

